# Capstone Project Final Assignment-Notebook

## Importing libraries

In [3]:
import requests # to handle requests
import pandas as pd # for data analsysis
import numpy as np # to handle data in a vectorized manner

!conda install -c conda-forge geopy --yes 
from geopy.geocoders import Nominatim # module to convert an address into latitude and longitude values

# libraries for displaying images
from IPython.display import Image 
from IPython.core.display import HTML 
    
#tranforming json file into a pandas dataframe library
from pandas.io.json import json_normalize

!conda install -c conda-forge folium=0.5.0 --yes
import folium # plotting library

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.7.10

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/jupyterlab/conda/envs/python

  added / updated specs:
    - geopy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    geopy-1.20.0               |             py_0          57 KB  conda-forge
    geographiclib-1.49         |             py_0          32 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          90 KB

The following NEW packages will be INSTALLED:

    geographiclib: 1.49-py_0   conda-forge
    geopy:         1.20.0-py_0 conda-forge


Downloading and Extracting Packages
geopy-1.20.0         | 57 KB     | ##################################### | 100%
geographiclib-1.49   | 32 KB     | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.7.10

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

## Define foursquare credentials

In [5]:
ClIENT_ID = 'GYGRB1EBUFAGQNNGJGPM2MRCTKHDALF02VF0SAXOZOTMC24K' # your Foursquare ID
ClIENT_SECRET = 'UX3FG20LW1ADYBLJR0VFLTVY1BASSPBQDRLYDK4G1GBPHVJK' # your Foursquare Secret
VERSION = '20180604'
LIMIT =30
print('Your credentails:')
print('Foursquare_ID: ' + ClIENT_ID)
print('Foursquare_Secret:' + ClIENT_SECRET)

Your credentails:
Foursquare_ID: GYGRB1EBUFAGQNNGJGPM2MRCTKHDALF02VF0SAXOZOTMC24K
Foursquare_Secret:UX3FG20LW1ADYBLJR0VFLTVY1BASSPBQDRLYDK4G1GBPHVJK

## Define the city and get its latitude & longitude

In [6]:
# define the city and get its latitude & longitude 
city = 'Toronto'
geolocator = Nominatim(user_agent="foursquare_agent")
location = geolocator.geocode(city)
latitude = location.latitude
longitude = location.longitude
print(latitude, longitude)

43.653963 -79.387207

## Search for Hotels

In [7]:
# search for hotels
search_query = 'Hotel'
radius = 500

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'\
.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=GYGRB1EBUFAGQNNGJGPM2MRCTKHDALF02VF0SAXOZOTMC24K&client_secret=UX3FG20LW1ADYBLJR0VFLTVY1BASSPBQDRLYDK4G1GBPHVJK&ll=43.653963,-79.387207&v=20180604&query=Hotel&radius=500&limit=30'

In [8]:
# Send the GET Request and examine the results
results = requests.get(url).json()

In [9]:
# assign relevant part of JSON to venues
venues = results['response']['venues']

# tranform venues into a dataframe
dataframe = json_normalize(venues)
dataframe.head()

,id,name,categories,referralId,hasPerk,location.address,location.crossStreet,location.lat,location.lng,location.labeledLatLngs,location.distance,location.postalCode,location.cc,location.city,location.state,location.country,location.formattedAddress,venuePage.id,location.neighborhood
0,4ab2d511f964a5209b6c20e3,Sheraton Centre Toronto Hotel,"[{'id': '4bf58dd8d48988d1fa931735', 'name': 'H...",v-1564039750,False,123 Queen Street West,at York St.,43.651129,-79.383829,"[{'label': 'display', 'lat': 43.65112928325278...",416,M5H 2M9,CA,Toronto,ON,Canada,"[123 Queen Street West (at York St.), Toronto ...",NaN,NaN
1,4b68aed1f964a520de862be3,The Rex Hotel Jazz & Blues Bar,"[{'id': '4bf58dd8d48988d1e7931735', 'name': 'J...",v-1564039750,False,194 Queen St W,Queen & St. Patrick,43.650505,-79.388577,"[{'label': 'display', 'lat': 43.65050475544005...",400,M5V 1Z1,CA,Toronto,ON,Canada,"[194 Queen St W (Queen & St. Patrick), Toronto...",62225795,NaN
2,58b7d72dcc05d161570bd712,Sheraton Centre Toronto Hotel,"[{'id': '4bf58dd8d48988d1fa931735', 'name': 'H...",v-1564039750,False,123 Queen Street West,NaN,43.651016,-79.384148,"[{'label': 'display', 'lat': 43.65101646682632...",410,M5H 2M9,CA,Toronto,ON,Canada,"[123 Queen Street West, Toronto ON M5H 2M9, Ca...",402127087,NaN
3,52ce14b0498e50457ce11780,DoubleTree by Hilton Hotel Toronto Downtown,"[{'id': '4bf58dd8d48988d1fa931735', 'name': 'H...",v-1564039750,False,108 Chestnut Street,Dundas St W,43.654608,-79.385942,"[{'label': 'display', 'lat': 43.6546083, 'lng'...",124,M5G 1R3,CA,Toronto,ON,Canada,"[108 Chestnut Street (Dundas St W), Toronto ON...",NaN,NaN
4,4f343a31e4b0230a3b337a90,VFM Test Hotel,"[{'id': '4bf58dd8d48988d1fa931735', 'name': 'H...",v-1564039750,False,123 Test Drive,at somewhere St,43.658434,-79.387894,"[{'label': 'display', 'lat': 43.658434, 'lng':...",500,M2M 2M2,CA,Toronto,ON,Canada,"[123 Test Drive (at somewhere St), Toronto ON ...",NaN,NaN

In [10]:
# keep only columns that include venue name, and anything that is associated with location
clean_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')]+ ['id']
clean_dataframe = dataframe.loc[:,clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row
clean_dataframe['categories'] = clean_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_dataframe.columns = [column.split('.')[-1] for column in clean_dataframe.columns]

clean_dataframe.head()

,name,categories,address,crossStreet,lat,lng,labeledLatLngs,distance,postalCode,cc,city,state,country,formattedAddress,neighborhood,id
0,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,at York St.,43.651129,-79.383829,"[{'label': 'display', 'lat': 43.65112928325278...",416,M5H 2M9,CA,Toronto,ON,Canada,"[123 Queen Street West (at York St.), Toronto ...",NaN,4ab2d511f964a5209b6c20e3
1,The Rex Hotel Jazz & Blues Bar,Jazz Club,194 Queen St W,Queen & St. Patrick,43.650505,-79.388577,"[{'label': 'display', 'lat': 43.65050475544005...",400,M5V 1Z1,CA,Toronto,ON,Canada,"[194 Queen St W (Queen & St. Patrick), Toronto...",NaN,4b68aed1f964a520de862be3
2,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,NaN,43.651016,-79.384148,"[{'label': 'display', 'lat': 43.65101646682632...",410,M5H 2M9,CA,Toronto,ON,Canada,"[123 Queen Street West, Toronto ON M5H 2M9, Ca...",NaN,58b7d72dcc05d161570bd712
3,DoubleTree by Hilton Hotel Toronto Downtown,Hotel,108 Chestnut Street,Dundas St W,43.654608,-79.385942,"[{'label': 'display', 'lat': 43.6546083, 'lng'...",124,M5G 1R3,CA,Toronto,ON,Canada,"[108 Chestnut Street (Dundas St W), Toronto ON...",NaN,52ce14b0498e50457ce11780
4,VFM Test Hotel,Hotel,123 Test Drive,at somewhere St,43.658434,-79.387894,"[{'label': 'display', 'lat': 43.658434, 'lng':...",500,M2M 2M2,CA,Toronto,ON,Canada,"[123 Test Drive (at somewhere St), Toronto ON ...",NaN,4f343a31e4b0230a3b337a90

In [11]:
# delete unnecessary columns
clean_dataframe2= clean_dataframe.drop(['cc', 'city', 'country', 'crossStreet', 'distance', 'formattedAddress',\
                                        'labeledLatLngs','neighborhood', 'id'], axis=1)
clean_dataframe2

,name,categories,address,lat,lng,postalCode,state
0,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,43.651129,-79.383829,M5H 2M9,ON
1,The Rex Hotel Jazz & Blues Bar,Jazz Club,194 Queen St W,43.650505,-79.388577,M5V 1Z1,ON
2,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,43.651016,-79.384148,M5H 2M9,ON
3,DoubleTree by Hilton Hotel Toronto Downtown,Hotel,108 Chestnut Street,43.654608,-79.385942,M5G 1R3,ON
4,VFM Test Hotel,Hotel,123 Test Drive,43.658434,-79.387894,M2M 2M2,ON
5,Sheraton Centre Toronto Hotel - Grand Ballroom,Ballroom,123 Queen Street West,43.651200,-79.384520,NaN,ON
6,Stathcona Hotel,Hotel,NaN,43.654947,-79.386359,NaN,ON
7,Shangri-La Toronto,Hotel,188 University Ave.,43.649129,-79.386557,M5H 0A3,ON
8,Marriott Downtown at CF Toronto Eaton Centre,Hotel,525 Bay Street,43.654728,-79.382422,M5G 2L2,ON
9,89 Chestnut Residence,College Residence Hall,89 Chestnut St.,43.654160,-79.385291,M5G 1R1,ON
10,Be SixFifty Hotel,Hotel,650 Bay Street,43.657120,-79.384560,NaN,ON
11,"hilton hotel, richmondstreet E, 145, toronto",Hotel Pool,"Richmondstreet E, 145",43.650625,-79.385488,NaN,ON
12,Hilton Toronto,Hotel,145 Richmond St W,43.650143,-79.385488,M5H 2L2,ON
13,650 Hotel,Hotel,650 Bay Street,43.657046,-79.384411,NaN,ON
14,Op mijn hotelkamer In Toronto,Hotel,NaN,43.654235,-79.386208,NaN,ON
15,Fitness Centre,Gym,525 Bay St.,43.654690,-79.381739,M5G 2L2,ON
16,Lobby Lounge at the Shangri-La Toronto,Lounge,188 University Ave.,43.649155,-79.386546,M5H 0A3,ON
17,Pool,Pool,Intercontinental,43.650975,-79.384053,NaN,Ontario
18,Kumar For Men,Men's Store,Sheraton Centre,43.651044,-79.383302,M5H 2M9,ON
19,Grand Ballroom,Event Space,123 Queen St. W,43.651217,-79.383771,M5H 2M9,ON
20,Fitness Centre,Gym,Sheraton Centre,43.650985,-79.384002,M5H 2M9,ON
21,Bistro on Two,Breakfast Spot,123 Queen St. W,43.651011,-79.383658,M5H 2M9,ON

In [12]:
# delete rows with none values
clean_dataframe3 = clean_dataframe2.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
clean_dataframe3

,name,categories,address,lat,lng,postalCode,state
0,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,43.651129,-79.383829,M5H 2M9,ON
1,The Rex Hotel Jazz & Blues Bar,Jazz Club,194 Queen St W,43.650505,-79.388577,M5V 1Z1,ON
2,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,43.651016,-79.384148,M5H 2M9,ON
3,DoubleTree by Hilton Hotel Toronto Downtown,Hotel,108 Chestnut Street,43.654608,-79.385942,M5G 1R3,ON
4,VFM Test Hotel,Hotel,123 Test Drive,43.658434,-79.387894,M2M 2M2,ON
7,Shangri-La Toronto,Hotel,188 University Ave.,43.649129,-79.386557,M5H 0A3,ON
8,Marriott Downtown at CF Toronto Eaton Centre,Hotel,525 Bay Street,43.654728,-79.382422,M5G 2L2,ON
9,89 Chestnut Residence,College Residence Hall,89 Chestnut St.,43.654160,-79.385291,M5G 1R1,ON
12,Hilton Toronto,Hotel,145 Richmond St W,43.650143,-79.385488,M5H 2L2,ON
15,Fitness Centre,Gym,525 Bay St.,43.654690,-79.381739,M5G 2L2,ON
16,Lobby Lounge at the Shangri-La Toronto,Lounge,188 University Ave.,43.649155,-79.386546,M5H 0A3,ON
18,Kumar For Men,Men's Store,Sheraton Centre,43.651044,-79.383302,M5H 2M9,ON
19,Grand Ballroom,Event Space,123 Queen St. W,43.651217,-79.383771,M5H 2M9,ON
20,Fitness Centre,Gym,Sheraton Centre,43.650985,-79.384002,M5H 2M9,ON
21,Bistro on Two,Breakfast Spot,123 Queen St. W,43.651011,-79.383658,M5H 2M9,ON

In [14]:
# delete rows which its category is not Hotel or Event Space
array= ['Hotel', 'Event Space']
hotel_dataframe= clean_dataframe3.loc[clean_dataframe3['categories'].isin(array)]
hotel_dataframe

,name,categories,address,lat,lng,postalCode,state
0,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,43.651129,-79.383829,M5H 2M9,ON
2,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,43.651016,-79.384148,M5H 2M9,ON
3,DoubleTree by Hilton Hotel Toronto Downtown,Hotel,108 Chestnut Street,43.654608,-79.385942,M5G 1R3,ON
4,VFM Test Hotel,Hotel,123 Test Drive,43.658434,-79.387894,M2M 2M2,ON
7,Shangri-La Toronto,Hotel,188 University Ave.,43.649129,-79.386557,M5H 0A3,ON
8,Marriott Downtown at CF Toronto Eaton Centre,Hotel,525 Bay Street,43.654728,-79.382422,M5G 2L2,ON
12,Hilton Toronto,Hotel,145 Richmond St W,43.650143,-79.385488,M5H 2L2,ON
19,Grand Ballroom,Event Space,123 Queen St. W,43.651217,-79.383771,M5H 2M9,ON

In [15]:
# delete rows which has duplicate hotel's name
df_hotels = hotel_dataframe.drop_duplicates(subset='name', keep="first")
df_hotels

,name,categories,address,lat,lng,postalCode,state
0,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,43.651129,-79.383829,M5H 2M9,ON
3,DoubleTree by Hilton Hotel Toronto Downtown,Hotel,108 Chestnut Street,43.654608,-79.385942,M5G 1R3,ON
4,VFM Test Hotel,Hotel,123 Test Drive,43.658434,-79.387894,M2M 2M2,ON
7,Shangri-La Toronto,Hotel,188 University Ave.,43.649129,-79.386557,M5H 0A3,ON
8,Marriott Downtown at CF Toronto Eaton Centre,Hotel,525 Bay Street,43.654728,-79.382422,M5G 2L2,ON
12,Hilton Toronto,Hotel,145 Richmond St W,43.650143,-79.385488,M5H 2L2,ON
19,Grand Ballroom,Event Space,123 Queen St. W,43.651217,-79.383771,M5H 2M9,ON

In [16]:
# choose the hotel which has the same postalCode with the event space
df_hotel = df_hotels[df_hotels.postalCode == 'M5H 2M9']
df_hotel

,name,categories,address,lat,lng,postalCode,state
0,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,43.651129,-79.383829,M5H 2M9,ON
19,Grand Ballroom,Event Space,123 Queen St. W,43.651217,-79.383771,M5H 2M9,ON

## Search for Parks

In [17]:
# search for Parks
search_query = 'Park'
radius = 10000

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'\
.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=GYGRB1EBUFAGQNNGJGPM2MRCTKHDALF02VF0SAXOZOTMC24K&client_secret=UX3FG20LW1ADYBLJR0VFLTVY1BASSPBQDRLYDK4G1GBPHVJK&ll=43.653963,-79.387207&v=20180604&query=Park&radius=10000&limit=30'

In [18]:
# Send the GET Request and examine the results
presults = requests.get(url).json()
#presults

In [19]:
# assign relevant part of JSON to venues
venues = presults['response']['venues']

# tranform venues into a dataframe
park_dataframe = json_normalize(venues)
park_dataframe.head()

,id,name,categories,referralId,hasPerk,location.lat,location.lng,location.labeledLatLngs,location.distance,location.cc,location.city,location.state,location.country,location.formattedAddress,location.address,location.crossStreet,location.postalCode,venuePage.id,location.neighborhood
0,4b54deadf964a520a3d027e3,Grange Park,"[{'id': '4bf58dd8d48988d163941735', 'name': 'P...",v-1564040080,False,43.652488,-79.392053,"[{'label': 'display', 'lat': 43.65248755299856...",423,CA,Toronto,ON,Canada,"[btwn College, University, Queen & Spadina, To...",NaN,NaN,NaN,NaN,NaN
1,4b170e47f964a5208cc123e3,Queen's Park Subway Station,"[{'id': '4bf58dd8d48988d1fd931735', 'name': 'M...",v-1564040080,False,43.660006,-79.390272,"[{'label': 'display', 'lat': 43.66000635700919...",716,CA,Toronto,ON,Canada,"[691 University Ave (at College St), Toronto O...",691 University Ave,at College St,M5G 2P1,NaN,NaN
2,4ad4c05ef964a520bdf620e3,Trinity Bellwoods Park,"[{'id': '4bf58dd8d48988d163941735', 'name': 'P...",v-1564040080,False,43.647072,-79.413756,"[{'label': 'display', 'lat': 43.64707192840234...",2271,CA,Toronto,ON,Canada,"[1053 Dundas St. W. (at Gore Vale Ave.), Toron...",1053 Dundas St. W.,at Gore Vale Ave.,M5H 2N2,NaN,NaN
3,4bb3c91a2397b7134d9f38b3,Clarence Square Park,"[{'id': '4bf58dd8d48988d163941735', 'name': 'P...",v-1564040080,False,43.644222,-79.394230,"[{'label': 'display', 'lat': 43.64422227794523...",1223,CA,Toronto,ON,Canada,"[Spadina Ave (at Wellington St W), Toronto ON,...",Spadina Ave,at Wellington St W,NaN,NaN,NaN
4,4b797b48f964a520c6fb2ee3,Bellevue Square Park,"[{'id': '4bf58dd8d48988d163941735', 'name': 'P...",v-1564040080,False,43.653610,-79.402199,"[{'label': 'display', 'lat': 43.65361021143256...",1208,CA,Toronto,ON,Canada,"[btwn Bellevue & Augusta Ave., Toronto ON M5T ...",btwn Bellevue & Augusta Ave.,NaN,M5T 2N4,NaN,NaN

## Clean Park Dataframe

In [20]:
# keep only columns that include venue name, and anything that is associated with location
park_clean_columns = ['name', 'categories'] + [col for col in park_dataframe.columns if col.startswith('location.')]+ ['id']
clean_park_dataframe = park_dataframe.loc[:,park_clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list1 = row['categories']
    except:
        categories_list1 = row['venue.categories']
        
    if len(categories_list1) == 0:
        return None
    else:
        return categories_list1[0]['name']

# filter the category for each row
clean_park_dataframe['categories'] = clean_park_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_park_dataframe.columns = [column.split('.')[-1] for column in clean_park_dataframe.columns]

clean_park_dataframe.head()

,name,categories,lat,lng,labeledLatLngs,distance,cc,city,state,country,formattedAddress,address,crossStreet,postalCode,neighborhood,id
0,Grange Park,Park,43.652488,-79.392053,"[{'label': 'display', 'lat': 43.65248755299856...",423,CA,Toronto,ON,Canada,"[btwn College, University, Queen & Spadina, To...",NaN,NaN,NaN,NaN,4b54deadf964a520a3d027e3
1,Queen's Park Subway Station,Metro Station,43.660006,-79.390272,"[{'label': 'display', 'lat': 43.66000635700919...",716,CA,Toronto,ON,Canada,"[691 University Ave (at College St), Toronto O...",691 University Ave,at College St,M5G 2P1,NaN,4b170e47f964a5208cc123e3
2,Trinity Bellwoods Park,Park,43.647072,-79.413756,"[{'label': 'display', 'lat': 43.64707192840234...",2271,CA,Toronto,ON,Canada,"[1053 Dundas St. W. (at Gore Vale Ave.), Toron...",1053 Dundas St. W.,at Gore Vale Ave.,M5H 2N2,NaN,4ad4c05ef964a520bdf620e3
3,Clarence Square Park,Park,43.644222,-79.394230,"[{'label': 'display', 'lat': 43.64422227794523...",1223,CA,Toronto,ON,Canada,"[Spadina Ave (at Wellington St W), Toronto ON,...",Spadina Ave,at Wellington St W,NaN,NaN,4bb3c91a2397b7134d9f38b3
4,Bellevue Square Park,Park,43.653610,-79.402199,"[{'label': 'display', 'lat': 43.65361021143256...",1208,CA,Toronto,ON,Canada,"[btwn Bellevue & Augusta Ave., Toronto ON M5T ...",btwn Bellevue & Augusta Ave.,NaN,M5T 2N4,NaN,4b797b48f964a520c6fb2ee3

In [21]:
# delete unnecessary columns
clean_park_dataframe2= clean_park_dataframe.drop(['cc', 'city', 'country', 'crossStreet', 'distance', 'formattedAddress',\
                                        'neighborhood','labeledLatLngs', 'id'], axis=1)
clean_park_dataframe2

,name,categories,lat,lng,state,address,postalCode
0,Grange Park,Park,43.652488,-79.392053,ON,NaN,NaN
1,Queen's Park Subway Station,Metro Station,43.660006,-79.390272,ON,691 University Ave,M5G 2P1
2,Trinity Bellwoods Park,Park,43.647072,-79.413756,ON,1053 Dundas St. W.,M5H 2N2
3,Clarence Square Park,Park,43.644222,-79.394230,ON,Spadina Ave,NaN
4,Bellevue Square Park,Park,43.653610,-79.402199,ON,btwn Bellevue & Augusta Ave.,M5T 2N4
5,Berczy Park,Park,43.648048,-79.375172,ON,35 Wellington St. East,NaN
6,HTO Park,Park,43.637949,-79.387820,ON,Queen's Quay,NaN
7,Crunch Fitness - College Park,Gym / Fitness Center,43.659263,-79.382632,ON,382 Yonge Street,M5G 1S8
8,Queen's Park,Park,43.663946,-79.392180,ON,University Ave.,M5R 2E8
9,St. Andrews Playground / Dog Park,Park,43.647388,-79.398752,ON,450 Adelaide Street West,NaN
10,One Park Lane,Residential Building (Apartment / Condo),43.655442,-79.390056,ON,280 Simcoe St,M5T 2Y5
11,Riverdale Park East,Park,43.669951,-79.355493,ON,550 Broadview Ave,M4K 2P1
12,High Park,Park,43.646479,-79.463425,ON,1873 Bloor St. W,M6R 2Z3
13,Residences at College Park North,Residential Building (Apartment / Condo),43.659822,-79.385159,ON,763 Bay St.,M5G 2R3
14,Stanley Park,Park,43.642395,-79.409330,ON,King Street West,NaN
15,Barbara Hall Park,Park,43.666728,-79.381084,ON,519 Church Street,NaN
16,Coronation Park,Park,43.634553,-79.405403,ON,711 Lake Shore Blvd. W,M5V 3T7
17,TTC Streetcar #403 - Victoria park,Light Rail Station,43.650735,-79.386921,ON,NaN,NaN
18,Stanley Park (Dog Park),Dog Run,43.641668,-79.409269,ON,King Street West,NaN
19,Canoe Landing Park,Park,43.638762,-79.397067,ON,50 Fort York Blvd,M5V 3Z1
20,Riverdale Park West,Park,43.666048,-79.360941,ON,500 Gerrard St.,M5A 2H3
21,Roundhouse Park,Park,43.641745,-79.384279,ON,255 Bremner Blvd.,M5V 3M9
22,Parliament Square Park,Park,43.650264,-79.362195,ON,44 Parliament Street,NaN
23,GoodLife Fitness Toronto Bloor Park,Gym,43.671398,-79.384408,ON,8 Park Rd,M4W 3G8
24,Winchester Park,Playground,43.666231,-79.371631,ON,530 Ontario Street,NaN
25,Physiomed College Park,Medical Center,43.658528,-79.382169,ON,382 Yonge St,M5B 1S8
26,College Park,Shopping Mall,43.661237,-79.383603,ON,444 Yonge St,M5B 2H4
27,Cawthra Square Dog Park,Dog Run,43.666583,-79.380040,ON,519 Church St.,NaN
28,Dufferin Grove Park,Park,43.656052,-79.431915,ON,875 Dufferin St,M6H
29,Harbour Square Park,Park,43.639253,-79.378395,ON,25 Queens Quay West,NaN

In [22]:
# delete rows with none values
clean_park_dataframe3 = clean_park_dataframe2.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
clean_park_dataframe3

,name,categories,lat,lng,state,address,postalCode
1,Queen's Park Subway Station,Metro Station,43.660006,-79.390272,ON,691 University Ave,M5G 2P1
2,Trinity Bellwoods Park,Park,43.647072,-79.413756,ON,1053 Dundas St. W.,M5H 2N2
4,Bellevue Square Park,Park,43.653610,-79.402199,ON,btwn Bellevue & Augusta Ave.,M5T 2N4
7,Crunch Fitness - College Park,Gym / Fitness Center,43.659263,-79.382632,ON,382 Yonge Street,M5G 1S8
8,Queen's Park,Park,43.663946,-79.392180,ON,University Ave.,M5R 2E8
10,One Park Lane,Residential Building (Apartment / Condo),43.655442,-79.390056,ON,280 Simcoe St,M5T 2Y5
11,Riverdale Park East,Park,43.669951,-79.355493,ON,550 Broadview Ave,M4K 2P1
12,High Park,Park,43.646479,-79.463425,ON,1873 Bloor St. W,M6R 2Z3
13,Residences at College Park North,Residential Building (Apartment / Condo),43.659822,-79.385159,ON,763 Bay St.,M5G 2R3
16,Coronation Park,Park,43.634553,-79.405403,ON,711 Lake Shore Blvd. W,M5V 3T7
19,Canoe Landing Park,Park,43.638762,-79.397067,ON,50 Fort York Blvd,M5V 3Z1
20,Riverdale Park West,Park,43.666048,-79.360941,ON,500 Gerrard St.,M5A 2H3
21,Roundhouse Park,Park,43.641745,-79.384279,ON,255 Bremner Blvd.,M5V 3M9
23,GoodLife Fitness Toronto Bloor Park,Gym,43.671398,-79.384408,ON,8 Park Rd,M4W 3G8
25,Physiomed College Park,Medical Center,43.658528,-79.382169,ON,382 Yonge St,M5B 1S8
26,College Park,Shopping Mall,43.661237,-79.383603,ON,444 Yonge St,M5B 2H4
28,Dufferin Grove Park,Park,43.656052,-79.431915,ON,875 Dufferin St,M6H

,name,categories,lat,lng,state,address,postalCode
2,Trinity Bellwoods Park,Park,43.647072,-79.413756,ON,1053 Dundas St. W.,M5H 2N2
4,Bellevue Square Park,Park,43.653610,-79.402199,ON,btwn Bellevue & Augusta Ave.,M5T 2N4
8,Queen's Park,Park,43.663946,-79.392180,ON,University Ave.,M5R 2E8
11,Riverdale Park East,Park,43.669951,-79.355493,ON,550 Broadview Ave,M4K 2P1
12,High Park,Park,43.646479,-79.463425,ON,1873 Bloor St. W,M6R 2Z3
16,Coronation Park,Park,43.634553,-79.405403,ON,711 Lake Shore Blvd. W,M5V 3T7
19,Canoe Landing Park,Park,43.638762,-79.397067,ON,50 Fort York Blvd,M5V 3Z1
20,Riverdale Park West,Park,43.666048,-79.360941,ON,500 Gerrard St.,M5A 2H3
21,Roundhouse Park,Park,43.641745,-79.384279,ON,255 Bremner Blvd.,M5V 3M9
28,Dufferin Grove Park,Park,43.656052,-79.431915,ON,875 Dufferin St,M6H

In [25]:
# delete rows which its category is not Park
df_park = clean_park_dataframe3[clean_park_dataframe3.categories == 'Park']
df_park

,name,categories,lat,lng,state,address,postalCode
2,Trinity Bellwoods Park,Park,43.647072,-79.413756,ON,1053 Dundas St. W.,M5H 2N2
4,Bellevue Square Park,Park,43.653610,-79.402199,ON,btwn Bellevue & Augusta Ave.,M5T 2N4
8,Queen's Park,Park,43.663946,-79.392180,ON,University Ave.,M5R 2E8
11,Riverdale Park East,Park,43.669951,-79.355493,ON,550 Broadview Ave,M4K 2P1
12,High Park,Park,43.646479,-79.463425,ON,1873 Bloor St. W,M6R 2Z3
16,Coronation Park,Park,43.634553,-79.405403,ON,711 Lake Shore Blvd. W,M5V 3T7
19,Canoe Landing Park,Park,43.638762,-79.397067,ON,50 Fort York Blvd,M5V 3Z1
20,Riverdale Park West,Park,43.666048,-79.360941,ON,500 Gerrard St.,M5A 2H3
21,Roundhouse Park,Park,43.641745,-79.384279,ON,255 Bremner Blvd.,M5V 3M9
28,Dufferin Grove Park,Park,43.656052,-79.431915,ON,875 Dufferin St,M6H

## Search for Restaurants

In [26]:
# search for Restaurants
search_query = 'Restaurant'
radius = 10000

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=GYGRB1EBUFAGQNNGJGPM2MRCTKHDALF02VF0SAXOZOTMC24K&client_secret=UX3FG20LW1ADYBLJR0VFLTVY1BASSPBQDRLYDK4G1GBPHVJK&ll=43.653963,-79.387207&v=20180604&query=Restaurant&radius=10000&limit=30'

In [27]:
# Send the GET Request and examine the results
Rresults = requests.get(url).json()

In [28]:
# assign relevant part of JSON to venues
venues = Rresults['response']['venues']

# tranform venues into a dataframe
Restaurant_dataframe = json_normalize(venues)
Restaurant_dataframe.head()

,id,name,categories,referralId,hasPerk,location.address,location.lat,location.lng,location.labeledLatLngs,location.distance,location.postalCode,location.cc,location.city,location.state,location.country,location.formattedAddress,location.neighborhood,venuePage.id,location.crossStreet
0,4ad4c05ff964a52048f720e3,Hemispheres Restaurant & Bistro,"[{'id': '4bf58dd8d48988d14e941735', 'name': 'A...",v-1564040342,False,110 Chestnut Street,43.654884,-79.385931,"[{'label': 'display', 'lat': 43.65488413420439...",145,M5G 1R3,CA,Toronto,ON,Canada,"[110 Chestnut Street, Toronto ON M5G 1R3, Canada]",NaN,NaN,NaN
1,4b223f5af964a520ba4424e3,Azure Restaurant & Bar,"[{'id': '4bf58dd8d48988d1c4941735', 'name': 'R...",v-1564040342,False,225 Frnt St W,43.644749,-79.385113,"[{'label': 'display', 'lat': 43.64474919591934...",1039,M5V 2X3,CA,Toronto,ON,Canada,"[225 Frnt St W, Toronto ON M5V 2X3, Canada]",Entertainment District,136175835,NaN
2,4ad4c060f964a5207ff720e3,Rol San Restaurant 龍笙棧,"[{'id': '4bf58dd8d48988d1f5931735', 'name': 'D...",v-1564040342,False,323 Spadina Ave.,43.654318,-79.398650,"[{'label': 'display', 'lat': 43.65431754076345...",922,M5T 2E9,CA,Toronto,ON,Canada,"[323 Spadina Ave. (at D'Arcy St.), Toronto ON ...",Kensington Market,NaN,at D'Arcy St.
3,4ae29812f964a520288f21e3,Swatow Restaurant 汕頭小食家,"[{'id': '4bf58dd8d48988d145941735', 'name': 'C...",v-1564040342,False,309 Spadina Ave.,43.653866,-79.398334,"[{'label': 'display', 'lat': 43.65386562507761...",896,M5T 2E6,CA,Toronto,ON,Canada,[309 Spadina Ave. (btwn Dundas St. W & D'Arcy ...,NaN,NaN,btwn Dundas St. W & D'Arcy St.
4,4b072e9df964a52009f922e3,Sky Dragon Chinese Restaurant 龍翔酒樓,"[{'id': '4bf58dd8d48988d1f5931735', 'name': 'D...",v-1564040342,False,280 Spadina Ave.,43.652783,-79.398174,"[{'label': 'display', 'lat': 43.65278331265585...",892,NaN,CA,Toronto,ON,Canada,"[280 Spadina Ave. (at Dundas St. W.), Toronto ...",NaN,NaN,at Dundas St. W.

## Clean Restaurant Dataframe

In [30]:
# keep only columns that include venue name, and anything that is associated with location
Restaurant_clean_columns = ['name', 'categories'] + [col for col in Restaurant_dataframe.columns if col.startswith('location.')]+ ['id']
clean_Restaurant_dataframe = Restaurant_dataframe.loc[:,Restaurant_clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list3 = row['categories']
    except:
        categories_list3 = row['venue.categories']
        
    if len(categories_list3) == 0:
        return None
    else:
        return categories_list3[0]['name']

# filter the category for each row
clean_Restaurant_dataframe['categories'] = clean_Restaurant_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_Restaurant_dataframe.columns = [column.split('.')[-1] for column in clean_Restaurant_dataframe.columns]

clean_Restaurant_dataframe.head()

,name,categories,address,lat,lng,labeledLatLngs,distance,postalCode,cc,city,state,country,formattedAddress,neighborhood,crossStreet,id
0,Hemispheres Restaurant & Bistro,American Restaurant,110 Chestnut Street,43.654884,-79.385931,"[{'label': 'display', 'lat': 43.65488413420439...",145,M5G 1R3,CA,Toronto,ON,Canada,"[110 Chestnut Street, Toronto ON M5G 1R3, Canada]",NaN,NaN,4ad4c05ff964a52048f720e3
1,Azure Restaurant & Bar,Restaurant,225 Frnt St W,43.644749,-79.385113,"[{'label': 'display', 'lat': 43.64474919591934...",1039,M5V 2X3,CA,Toronto,ON,Canada,"[225 Frnt St W, Toronto ON M5V 2X3, Canada]",Entertainment District,NaN,4b223f5af964a520ba4424e3
2,Rol San Restaurant 龍笙棧,Dim Sum Restaurant,323 Spadina Ave.,43.654318,-79.398650,"[{'label': 'display', 'lat': 43.65431754076345...",922,M5T 2E9,CA,Toronto,ON,Canada,"[323 Spadina Ave. (at D'Arcy St.), Toronto ON ...",Kensington Market,at D'Arcy St.,4ad4c060f964a5207ff720e3
3,Swatow Restaurant 汕頭小食家,Chinese Restaurant,309 Spadina Ave.,43.653866,-79.398334,"[{'label': 'display', 'lat': 43.65386562507761...",896,M5T 2E6,CA,Toronto,ON,Canada,[309 Spadina Ave. (btwn Dundas St. W & D'Arcy ...,NaN,btwn Dundas St. W & D'Arcy St.,4ae29812f964a520288f21e3
4,Sky Dragon Chinese Restaurant 龍翔酒樓,Dim Sum Restaurant,280 Spadina Ave.,43.652783,-79.398174,"[{'label': 'display', 'lat': 43.65278331265585...",892,NaN,CA,Toronto,ON,Canada,"[280 Spadina Ave. (at Dundas St. W.), Toronto ...",NaN,at Dundas St. W.,4b072e9df964a52009f922e3

In [31]:
# delete unnecessary columns
clean_Restaurant_dataframe2= clean_Restaurant_dataframe.drop(['cc', 'city', 'country', 'crossStreet', 'distance', 'formattedAddress',\
                                        'labeledLatLngs', 'neighborhood', 'id'], axis=1)
clean_Restaurant_dataframe2

,name,categories,address,lat,lng,postalCode,state
0,Hemispheres Restaurant & Bistro,American Restaurant,110 Chestnut Street,43.654884,-79.385931,M5G 1R3,ON
1,Azure Restaurant & Bar,Restaurant,225 Frnt St W,43.644749,-79.385113,M5V 2X3,ON
2,Rol San Restaurant 龍笙棧,Dim Sum Restaurant,323 Spadina Ave.,43.654318,-79.398650,M5T 2E9,ON
3,Swatow Restaurant 汕頭小食家,Chinese Restaurant,309 Spadina Ave.,43.653866,-79.398334,M5T 2E6,ON
4,Sky Dragon Chinese Restaurant 龍翔酒樓,Dim Sum Restaurant,280 Spadina Ave.,43.652783,-79.398174,NaN,ON
5,Goldstone Noodle Restaurant 金石,Noodle House,266 Spadina Ave,43.652278,-79.398039,M5T 2E4,ON
6,360 Restaurant,Wine Bar,301 Front St W,43.642537,-79.387042,M5V 2T6,ON
7,Aroma Fine Indian Restaurant,Indian Restaurant,287 King St. W,43.646463,-79.389644,M5V 1J5,ON
8,New Sky Restaurant 小沙田食家,Chinese Restaurant,353 Spadina Ave.,43.655337,-79.398897,M5T 2G3,ON
9,Hong Shing Chinese Restaurant,Chinese Restaurant,195 Dundas St W,43.654925,-79.387089,M5G 1C7,ON
10,Victor Restaurant & Bar,Bar,30 Mercer Street,43.645634,-79.391125,M5V 1H3,ON
11,Green Tea Restaurant Downtown,Chinese Restaurant,261 Spadina Avenue. Upper level,43.652488,-79.397501,M5T 2E3,ON
12,The Hot House Restaurant & Bar,American Restaurant,35 Church St,43.648824,-79.373702,M5E 1T3,ON
13,Victoria's Restaurant,Restaurant,37 King Street East,43.649298,-79.376431,M5C 1E9,ON
14,Sassafraz | Cafe | Restaurant | Private Events,Event Space,100 Cumberland Street,43.670342,-79.391041,M5R 1A6,ON
15,Tasty's Caribbean Restaurant & Catering,Caribbean Restaurant,405 Spadina Ave,43.656794,-79.399251,M5T 2G6,ON
16,ONE Restaurant/Lounge,New American Restaurant,116 Yorkville Ave,43.670809,-79.393272,NaN,ON
17,North-East Chinese Restaurant 華北美食,Chinese Restaurant,476 Dundas St.,43.653185,-79.396677,NaN,ON
18,Richtree Natural Market Restaurants,Restaurant,14 Queen St W,43.652614,-79.380231,M5H 3X4,ON
19,The Lakeview Restaurant,Diner,1132 Dundas St. W,43.649435,-79.420390,M6J 1X2,ON
20,Insomnia Restaurant and Lounge,Restaurant,563 Bloor St West,43.665180,-79.410966,M5S 1Y6,ON
21,Ka Chi Korean Restaurant,Korean Restaurant,8 St Andrew St.,43.654307,-79.399277,M5T 1K6,ON
22,Woodlot Restaurant & Bakery,New American Restaurant,293 Palmerston Ave.,43.655765,-79.409929,M6J 2J3,ON
23,Matisse Restaurant And Bar,Restaurant,90 Bloor St.,43.670574,-79.384856,M4W 1A7,ON
24,Studio Restaurant,Breakfast Spot,389 Church St.,43.661500,-79.379319,M5B,ON
25,Union Restaurant,New American Restaurant,72 Ossington Ave.,43.645860,-79.419532,NaN,ON
26,The Senator Restaurant,Diner,249 Victoria Street,43.655641,-79.379199,M5B 1T8,ON
27,Kensington Cornerstone Restaurant,Breakfast Spot,2A Kensington Ave.,43.652803,-79.399958,M5T 2J7,ON
28,Tundra Restaurant,Restaurant,145 Richmond Street West,43.650010,-79.385608,M5H 2L2,ON
29,Cottage Restaurant & Lounge,Thai Restaurant,338 Jarvis St.,43.662770,-79.376894,M4Y 2G6,ON

In [32]:
# delete rows with none values
df_Restaurant = clean_Restaurant_dataframe2.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
df_Restaurant

,name,categories,address,lat,lng,postalCode,state
0,Hemispheres Restaurant & Bistro,American Restaurant,110 Chestnut Street,43.654884,-79.385931,M5G 1R3,ON
1,Azure Restaurant & Bar,Restaurant,225 Frnt St W,43.644749,-79.385113,M5V 2X3,ON
2,Rol San Restaurant 龍笙棧,Dim Sum Restaurant,323 Spadina Ave.,43.654318,-79.398650,M5T 2E9,ON
3,Swatow Restaurant 汕頭小食家,Chinese Restaurant,309 Spadina Ave.,43.653866,-79.398334,M5T 2E6,ON
5,Goldstone Noodle Restaurant 金石,Noodle House,266 Spadina Ave,43.652278,-79.398039,M5T 2E4,ON
6,360 Restaurant,Wine Bar,301 Front St W,43.642537,-79.387042,M5V 2T6,ON
7,Aroma Fine Indian Restaurant,Indian Restaurant,287 King St. W,43.646463,-79.389644,M5V 1J5,ON
8,New Sky Restaurant 小沙田食家,Chinese Restaurant,353 Spadina Ave.,43.655337,-79.398897,M5T 2G3,ON
9,Hong Shing Chinese Restaurant,Chinese Restaurant,195 Dundas St W,43.654925,-79.387089,M5G 1C7,ON
10,Victor Restaurant & Bar,Bar,30 Mercer Street,43.645634,-79.391125,M5V 1H3,ON
11,Green Tea Restaurant Downtown,Chinese Restaurant,261 Spadina Avenue. Upper level,43.652488,-79.397501,M5T 2E3,ON
12,The Hot House Restaurant & Bar,American Restaurant,35 Church St,43.648824,-79.373702,M5E 1T3,ON
13,Victoria's Restaurant,Restaurant,37 King Street East,43.649298,-79.376431,M5C 1E9,ON
14,Sassafraz | Cafe | Restaurant | Private Events,Event Space,100 Cumberland Street,43.670342,-79.391041,M5R 1A6,ON
15,Tasty's Caribbean Restaurant & Catering,Caribbean Restaurant,405 Spadina Ave,43.656794,-79.399251,M5T 2G6,ON
18,Richtree Natural Market Restaurants,Restaurant,14 Queen St W,43.652614,-79.380231,M5H 3X4,ON
19,The Lakeview Restaurant,Diner,1132 Dundas St. W,43.649435,-79.420390,M6J 1X2,ON
20,Insomnia Restaurant and Lounge,Restaurant,563 Bloor St West,43.665180,-79.410966,M5S 1Y6,ON
21,Ka Chi Korean Restaurant,Korean Restaurant,8 St Andrew St.,43.654307,-79.399277,M5T 1K6,ON
22,Woodlot Restaurant & Bakery,New American Restaurant,293 Palmerston Ave.,43.655765,-79.409929,M6J 2J3,ON
23,Matisse Restaurant And Bar,Restaurant,90 Bloor St.,43.670574,-79.384856,M4W 1A7,ON
24,Studio Restaurant,Breakfast Spot,389 Church St.,43.661500,-79.379319,M5B,ON
26,The Senator Restaurant,Diner,249 Victoria Street,43.655641,-79.379199,M5B 1T8,ON
27,Kensington Cornerstone Restaurant,Breakfast Spot,2A Kensington Ave.,43.652803,-79.399958,M5T 2J7,ON
28,Tundra Restaurant,Restaurant,145 Richmond Street West,43.650010,-79.385608,M5H 2L2,ON
29,Cottage Restaurant & Lounge,Thai Restaurant,338 Jarvis St.,43.662770,-79.376894,M4Y 2G6,ON

## Search for Cafeteria

In [33]:
# search for Cafeteria
search_query = 'Cafeteria'
radius = 10000

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=GYGRB1EBUFAGQNNGJGPM2MRCTKHDALF02VF0SAXOZOTMC24K&client_secret=UX3FG20LW1ADYBLJR0VFLTVY1BASSPBQDRLYDK4G1GBPHVJK&ll=43.653963,-79.387207&v=20180604&query=Cafeteria&radius=10000&limit=30'

In [34]:
# Send the GET Request and examine the results
cresults = requests.get(url).json()
#cresults

In [35]:
# assign relevant part of JSON to venues
venues = cresults['response']['venues']

# tranform venues into a dataframe
Cafeteria_dataframe = json_normalize(venues)
Cafeteria_dataframe.head()

,id,name,categories,referralId,hasPerk,location.address,location.lat,location.lng,location.labeledLatLngs,location.distance,location.cc,location.city,location.state,location.country,location.formattedAddress,location.crossStreet,location.postalCode
0,4f9165bde4b04fef0087e4e2,Cafeteria,"[{'id': '4bf58dd8d48988d16e941735', 'name': 'F...",v-1564040563,False,The Hospital for Sick Children (SickKids),43.657209,-79.386063,"[{'label': 'display', 'lat': 43.65720930549997...",372,CA,Toronto,ON,Canada,"[The Hospital for Sick Children (SickKids), To...",NaN,NaN
1,528e99a211d262edc3708a6f,Stay Cafeteria 慢走,"[{'id': '4bf58dd8d48988d142941735', 'name': 'A...",v-1564040563,False,388 Spadina Ave,43.655454,-79.399163,"[{'label': 'display', 'lat': 43.65545427446646...",977,CA,Toronto,ON,Canada,"[388 Spadina Ave (at Nassau St), Toronto ON M5...",at Nassau St,M5T 2G5
2,4ec2b68a8231a83de8c45191,OCAD Cafeteria,"[{'id': '4bf58dd8d48988d1a1941735', 'name': 'C...",v-1564040563,False,100 McCaul St.,43.652780,-79.391762,"[{'label': 'display', 'lat': 43.65278016892648...",389,CA,Toronto,ON,Canada,"[100 McCaul St. (Second Floor), Toronto ON, Ca...",Second Floor,NaN
3,56b2c90a498e9f0e73d6bed6,Cafeteria,"[{'id': '4bf58dd8d48988d1c1941735', 'name': 'M...",v-1564040563,False,974 College St,43.653419,-79.427678,"[{'label': 'display', 'lat': 43.65341883567197...",3260,CA,Toronto,ON,Canada,"[974 College St, Toronto ON M6H 1A5, Canada]",NaN,M6H 1A5
4,53bd6dfe498e6c1d3bc9333e,Industrial Alliance Cafeteria,"[{'id': '4bf58dd8d48988d128941735', 'name': 'C...",v-1564040563,False,NaN,43.655657,-79.389443,"[{'label': 'display', 'lat': 43.655657, 'lng':...",260,CA,Toronto,ON,Canada,"[Toronto ON, Canada]",NaN,NaN

## Clean Cafeteria Dataframe

In [36]:
# keep only columns that include venue name, and anything that is associated with location
Cafeteria_clean_columns = ['name', 'categories'] + [col for col in Cafeteria_dataframe.columns if col.startswith('location.')]+ ['id']
clean_Cafeteria_dataframe = Cafeteria_dataframe.loc[:,Cafeteria_clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list4 = row['categories']
    except:
        categories_list4 = row['venue.categories']
        
    if len(categories_list4) == 0:
        return None
    else:
        return categories_list4[0]['name']

# filter the category for each row
clean_Cafeteria_dataframe['categories'] = clean_Cafeteria_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_Cafeteria_dataframe.columns = [column.split('.')[-1] for column in clean_Cafeteria_dataframe.columns]

clean_Cafeteria_dataframe.head()

,name,categories,address,lat,lng,labeledLatLngs,distance,cc,city,state,country,formattedAddress,crossStreet,postalCode,id
0,Cafeteria,Fast Food Restaurant,The Hospital for Sick Children (SickKids),43.657209,-79.386063,"[{'label': 'display', 'lat': 43.65720930549997...",372,CA,Toronto,ON,Canada,"[The Hospital for Sick Children (SickKids), To...",NaN,NaN,4f9165bde4b04fef0087e4e2
1,Stay Cafeteria 慢走,Asian Restaurant,388 Spadina Ave,43.655454,-79.399163,"[{'label': 'display', 'lat': 43.65545427446646...",977,CA,Toronto,ON,Canada,"[388 Spadina Ave (at Nassau St), Toronto ON M5...",at Nassau St,M5T 2G5,528e99a211d262edc3708a6f
2,OCAD Cafeteria,College Cafeteria,100 McCaul St.,43.652780,-79.391762,"[{'label': 'display', 'lat': 43.65278016892648...",389,CA,Toronto,ON,Canada,"[100 McCaul St. (Second Floor), Toronto ON, Ca...",Second Floor,NaN,4ec2b68a8231a83de8c45191
3,Cafeteria,Mexican Restaurant,974 College St,43.653419,-79.427678,"[{'label': 'display', 'lat': 43.65341883567197...",3260,CA,Toronto,ON,Canada,"[974 College St, Toronto ON M6H 1A5, Canada]",NaN,M6H 1A5,56b2c90a498e9f0e73d6bed6
4,Industrial Alliance Cafeteria,Cafeteria,NaN,43.655657,-79.389443,"[{'label': 'display', 'lat': 43.655657, 'lng':...",260,CA,Toronto,ON,Canada,"[Toronto ON, Canada]",NaN,NaN,53bd6dfe498e6c1d3bc9333e

In [37]:
# delete unnecessary columns
clean_Cafeteria_dataframe2= clean_Cafeteria_dataframe.drop(['cc', 'city', 'country', 'crossStreet', 'distance', 'formattedAddress',\
                                        'labeledLatLngs', 'id'], axis=1)
clean_Cafeteria_dataframe2

,name,categories,address,lat,lng,state,postalCode
0,Cafeteria,Fast Food Restaurant,The Hospital for Sick Children (SickKids),43.657209,-79.386063,ON,NaN
1,Stay Cafeteria 慢走,Asian Restaurant,388 Spadina Ave,43.655454,-79.399163,ON,M5T 2G5
2,OCAD Cafeteria,College Cafeteria,100 McCaul St.,43.652780,-79.391762,ON,NaN
3,Cafeteria,Mexican Restaurant,974 College St,43.653419,-79.427678,ON,M6H 1A5
4,Industrial Alliance Cafeteria,Cafeteria,NaN,43.655657,-79.389443,ON,NaN
5,Ryerson Hub Cafeteria,College Cafeteria,350 Victoria St.,43.658475,-79.377653,ON,NaN
6,Dears Cafeteria,Dessert Shop,NaN,43.654179,-79.392555,NaN,NaN
7,Chestnut Tree Cafeteria,Cafeteria,89 Chestnut Street,43.648231,-79.384045,ON,NaN
8,Sears Cafeteria,Food Court,Yonge,43.656038,-79.380672,ON,NaN
9,De La Salle College Cafeteria,College Cafeteria,131 Farnham Avenue,43.683003,-79.397815,ON,M4V 1H7
10,Med Sci Cafeteria,College Cafeteria,NaN,43.660260,-79.392977,ON,NaN
11,SickKids Cafeteria,Food Court,555 University Avenue,43.657584,-79.375652,ON,NaN
12,Macdonald Block Cafeteria,Cafeteria,NaN,43.663212,-79.388062,NaN,NaN
13,Robarts Cafeteria,College Cafeteria,130 St. George St.,43.664864,-79.399766,ON,NaN
14,George Brown College St. James Campus,Community College,51 Dockside Dr,43.644163,-79.366375,ON,M5A 0B6
15,OMP Cafeteria,Cafeteria,1 Mount Pleasant,43.669801,-79.379790,ON,NaN
16,Rogers Cafeteria,Food Court,NaN,43.669904,-79.379748,ON,NaN
17,Choices Cafeteria,Food Court,200 Bloor Street E,43.671411,-79.381849,ON,NaN
18,"Cafeteria, Lawrence Park Collegiate",High School,NaN,43.721732,-79.409600,NaN,NaN
19,Kasala Cafeteria,African Restaurant,Bloor,43.660759,-79.424018,NaN,NaN
20,"Cafeteria, Lawrence Park Collegiate",Event Space,NaN,43.723286,-79.412222,NaN,NaN
21,Estonian House Cafeteria,Café,958 Broadview avenue,43.681763,-79.358246,ON,NaN
22,Marketeria,Restaurant,30 Bond St.,43.653585,-79.378843,ON,M5B 1W8
23,The Hub,College Cafeteria,350 Victoria St.,43.658585,-79.380622,ON,M5B 2K3
24,CC Cafeteria,College Cafeteria,951 Carlaw Ave,43.684631,-79.348862,ON,NaN
25,Innis College,Student Center,2 Sussex Ave,43.665556,-79.399298,ON,M5S 1J5
26,One Hour,Chinese Restaurant,435 Spadina Ave.,43.657399,-79.399649,ON,M5T 2T6
27,Radio Cafe,Food Court,333 Bloor st east,43.671696,-79.380617,ON,NaN
28,Lawrence Park Collegiate Cafeteria,High School,NaN,43.722757,-79.413734,ON,NaN
29,L5 Cafeteria,Cuban Restaurant,NaN,43.723019,-79.345012,NaN,NaN

In [38]:
# delete rows with none values
df_Cafeteria = clean_Cafeteria_dataframe2.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
df_Cafeteria

,name,categories,address,lat,lng,state,postalCode
1,Stay Cafeteria 慢走,Asian Restaurant,388 Spadina Ave,43.655454,-79.399163,ON,M5T 2G5
3,Cafeteria,Mexican Restaurant,974 College St,43.653419,-79.427678,ON,M6H 1A5
9,De La Salle College Cafeteria,College Cafeteria,131 Farnham Avenue,43.683003,-79.397815,ON,M4V 1H7
14,George Brown College St. James Campus,Community College,51 Dockside Dr,43.644163,-79.366375,ON,M5A 0B6
22,Marketeria,Restaurant,30 Bond St.,43.653585,-79.378843,ON,M5B 1W8
23,The Hub,College Cafeteria,350 Victoria St.,43.658585,-79.380622,ON,M5B 2K3
25,Innis College,Student Center,2 Sussex Ave,43.665556,-79.399298,ON,M5S 1J5
26,One Hour,Chinese Restaurant,435 Spadina Ave.,43.657399,-79.399649,ON,M5T 2T6

## Search for Shopping Stores

In [39]:
# search for Shopping stores
search_query = 'Shopping'
radius = 1000

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=GYGRB1EBUFAGQNNGJGPM2MRCTKHDALF02VF0SAXOZOTMC24K&client_secret=UX3FG20LW1ADYBLJR0VFLTVY1BASSPBQDRLYDK4G1GBPHVJK&ll=43.653963,-79.387207&v=20180604&query=Shopping&radius=1000&limit=30'

In [40]:
# Send the GET Request and examine the results
sresults = requests.get(url).json()

In [41]:
# assign relevant part of JSON to venues
venues = sresults['response']['venues']

# tranform venues into a dataframe
Shopping_dataframe = json_normalize(venues)
Shopping_dataframe.head()

,id,name,categories,referralId,hasPerk,location.address,location.crossStreet,location.lat,location.lng,location.labeledLatLngs,location.distance,location.postalCode,location.cc,location.city,location.state,location.country,location.formattedAddress,location.neighborhood
0,4ad4c062f964a520fcf720e3,Dragon City Shopping Mall 龍城,"[{'id': '4bf58dd8d48988d1fd941735', 'name': 'S...",v-1564040760,False,280 Spadina Ave,at Dundas St W,43.652774,-79.398222,"[{'label': 'display', 'lat': 43.65277367198862...",897,M5T 3A5,CA,Toronto,ON,Canada,"[280 Spadina Ave (at Dundas St W), Toronto ON ...",NaN
1,4ad77a12f964a520260b21e3,CF Toronto Eaton Centre,"[{'id': '4bf58dd8d48988d1fd941735', 'name': 'S...",v-1564040760,False,220 Yonge St,btwn Queen & Dundas,43.653779,-79.380699,NaN,524,M5B 2H1,CA,Toronto,ON,Canada,"[220 Yonge St (btwn Queen & Dundas), Toronto O...","Downtown Toronto, Toronto, ON"
2,4b9e86dff964a520e6eb36e3,TD Centre Shopping Concourse,"[{'id': '4bf58dd8d48988d1fd941735', 'name': 'S...",v-1564040760,False,66 Wellington St W,btw York & Bay St,43.647184,-79.380932,"[{'label': 'display', 'lat': 43.64718424611984...",908,M5K 1A1,CA,Toronto,ON,Canada,"[66 Wellington St W (btw York & Bay St), Toron...",NaN
3,5840cafe06f1a34af80cc609,Saks Fifth Avenue Club - Personal Shopping,"[{'id': '4bf58dd8d48988d1f6941735', 'name': 'D...",v-1564040760,False,176 Yonge Street,Queen Street West,43.651810,-79.379192,"[{'label': 'display', 'lat': 43.65181, 'lng': ...",688,M5C 2L7,CA,Toronto,ON,Canada,"[176 Yonge Street (Queen Street West), Toronto...",NaN
4,4b83d653f964a520d91231e3,Yellow Pages - RedFlagDeals.com,"[{'id': '4bf58dd8d48988d124941735', 'name': 'O...",v-1564040760,False,461 King St. West,NaN,43.647958,-79.396006,"[{'label': 'display', 'lat': 43.64795765580337...",974,M5V 1K4,CA,Toronto,ON,Canada,"[461 King St. West, Toronto ON M5V 1K4, Canada]",NaN

## Clean Shopping Dataframe

In [42]:
# keep only columns that include venue name, and anything that is associated with location
Shopping_clean_columns = ['name', 'categories'] + [col for col in Shopping_dataframe.columns if col.startswith('location.')]+ ['id']
clean_Shopping_dataframe = Shopping_dataframe.loc[:,Shopping_clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list5 = row['categories']
    except:
        categories_list5 = row['venue.categories']
        
    if len(categories_list5) == 0:
        return None
    else:
        return categories_list5[0]['name']

# filter the category for each row
clean_Shopping_dataframe['categories'] = clean_Shopping_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_Shopping_dataframe.columns = [column.split('.')[-1] for column in clean_Shopping_dataframe.columns]

clean_Shopping_dataframe.head()

,name,categories,address,crossStreet,lat,lng,labeledLatLngs,distance,postalCode,cc,city,state,country,formattedAddress,neighborhood,id
0,Dragon City Shopping Mall 龍城,Shopping Mall,280 Spadina Ave,at Dundas St W,43.652774,-79.398222,"[{'label': 'display', 'lat': 43.65277367198862...",897,M5T 3A5,CA,Toronto,ON,Canada,"[280 Spadina Ave (at Dundas St W), Toronto ON ...",NaN,4ad4c062f964a520fcf720e3
1,CF Toronto Eaton Centre,Shopping Mall,220 Yonge St,btwn Queen & Dundas,43.653779,-79.380699,NaN,524,M5B 2H1,CA,Toronto,ON,Canada,"[220 Yonge St (btwn Queen & Dundas), Toronto O...","Downtown Toronto, Toronto, ON",4ad77a12f964a520260b21e3
2,TD Centre Shopping Concourse,Shopping Mall,66 Wellington St W,btw York & Bay St,43.647184,-79.380932,"[{'label': 'display', 'lat': 43.64718424611984...",908,M5K 1A1,CA,Toronto,ON,Canada,"[66 Wellington St W (btw York & Bay St), Toron...",NaN,4b9e86dff964a520e6eb36e3
3,Saks Fifth Avenue Club - Personal Shopping,Department Store,176 Yonge Street,Queen Street West,43.651810,-79.379192,"[{'label': 'display', 'lat': 43.65181, 'lng': ...",688,M5C 2L7,CA,Toronto,ON,Canada,"[176 Yonge Street (Queen Street West), Toronto...",NaN,5840cafe06f1a34af80cc609
4,Yellow Pages - RedFlagDeals.com,Office,461 King St. West,NaN,43.647958,-79.396006,"[{'label': 'display', 'lat': 43.64795765580337...",974,M5V 1K4,CA,Toronto,ON,Canada,"[461 King St. West, Toronto ON M5V 1K4, Canada]",NaN,4b83d653f964a520d91231e3

In [43]:
# delete unnecessary columns
clean_Shopping_dataframe2= clean_Shopping_dataframe.drop(['cc', 'city', 'country', 'crossStreet', 'distance', 'formattedAddress',\
                                        'labeledLatLngs', 'neighborhood', 'id'], axis=1)
clean_Shopping_dataframe2

,name,categories,address,lat,lng,postalCode,state
0,Dragon City Shopping Mall 龍城,Shopping Mall,280 Spadina Ave,43.652774,-79.398222,M5T 3A5,ON
1,CF Toronto Eaton Centre,Shopping Mall,220 Yonge St,43.653779,-79.380699,M5B 2H1,ON
2,TD Centre Shopping Concourse,Shopping Mall,66 Wellington St W,43.647184,-79.380932,M5K 1A1,ON
3,Saks Fifth Avenue Club - Personal Shopping,Department Store,176 Yonge Street,43.651810,-79.379192,M5C 2L7,ON
4,Yellow Pages - RedFlagDeals.com,Office,461 King St. West,43.647958,-79.396006,M5V 1K4,ON

In [44]:
# delete rows which its category is not Shopping Mall
df_Shopping = clean_Shopping_dataframe2[clean_Shopping_dataframe2.categories == 'Shopping Mall']
df_Shopping

,name,categories,address,lat,lng,postalCode,state
0,Dragon City Shopping Mall 龍城,Shopping Mall,280 Spadina Ave,43.652774,-79.398222,M5T 3A5,ON
1,CF Toronto Eaton Centre,Shopping Mall,220 Yonge St,43.653779,-79.380699,M5B 2H1,ON
2,TD Centre Shopping Concourse,Shopping Mall,66 Wellington St W,43.647184,-79.380932,M5K 1A1,ON

## Generate map to visualize hotels, shopping stores and Cafeteria and how they cluster together

In [45]:
# create dataframe of hotels, shopping stores and Cafeteria dataframes concatenated together
hotel_neighbourhood_df = pd.concat([df_hotel, df_Cafeteria, df_Shopping], ignore_index=True)
hotel_neighbourhood_df

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,address,categories,lat,lng,name,postalCode,state
0,123 Queen Street West,Hotel,43.651129,-79.383829,Sheraton Centre Toronto Hotel,M5H 2M9,ON
1,123 Queen St. W,Event Space,43.651217,-79.383771,Grand Ballroom,M5H 2M9,ON
2,388 Spadina Ave,Asian Restaurant,43.655454,-79.399163,Stay Cafeteria 慢走,M5T 2G5,ON
3,974 College St,Mexican Restaurant,43.653419,-79.427678,Cafeteria,M6H 1A5,ON
4,131 Farnham Avenue,College Cafeteria,43.683003,-79.397815,De La Salle College Cafeteria,M4V 1H7,ON
5,51 Dockside Dr,Community College,43.644163,-79.366375,George Brown College St. James Campus,M5A 0B6,ON
6,30 Bond St.,Restaurant,43.653585,-79.378843,Marketeria,M5B 1W8,ON
7,350 Victoria St.,College Cafeteria,43.658585,-79.380622,The Hub,M5B 2K3,ON
8,2 Sussex Ave,Student Center,43.665556,-79.399298,Innis College,M5S 1J5,ON
9,435 Spadina Ave.,Chinese Restaurant,43.657399,-79.399649,One Hour,M5T 2T6,ON
10,280 Spadina Ave,Shopping Mall,43.652774,-79.398222,Dragon City Shopping Mall 龍城,M5T 3A5,ON
11,220 Yonge St,Shopping Mall,43.653779,-79.380699,CF Toronto Eaton Centre,M5B 2H1,ON
12,66 Wellington St W,Shopping Mall,43.647184,-79.380932,TD Centre Shopping Concourse,M5K 1A1,ON

In [46]:
# Generate map to visualize hotel neighbourhood including shopping stores and Cafeteria 
hotel_map = folium.Map(location=[latitude, longitude], zoom_start=14)

for lat, lng, name, categories, address in zip(hotel_neighbourhood_df['lat'], hotel_neighbourhood_df['lng'], 
                                           hotel_neighbourhood_df['name'], hotel_neighbourhood_df['categories'],\
                                               hotel_neighbourhood_df['address']):
    label = '{}, {}'.format(name, address)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='blue',
        fill_opacity=0.7,
        parse_html=False).add_to(hotel_map)  
    
hotel_map

## Generate map to visualize Park, Restaurant and Cafeteria and how they cluster together

In [47]:
# create dataframe of Park, Restaurant and Cafeteria
park_neighbourhood_df = pd.concat([df_park, df_Restaurant, df_Cafeteria,], ignore_index=True)
park_neighbourhood_df

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,address,categories,lat,lng,name,postalCode,state
0,1053 Dundas St. W.,Park,43.647072,-79.413756,Trinity Bellwoods Park,M5H 2N2,ON
1,btwn Bellevue & Augusta Ave.,Park,43.653610,-79.402199,Bellevue Square Park,M5T 2N4,ON
2,University Ave.,Park,43.663946,-79.392180,Queen's Park,M5R 2E8,ON
3,550 Broadview Ave,Park,43.669951,-79.355493,Riverdale Park East,M4K 2P1,ON
4,1873 Bloor St. W,Park,43.646479,-79.463425,High Park,M6R 2Z3,ON
5,711 Lake Shore Blvd. W,Park,43.634553,-79.405403,Coronation Park,M5V 3T7,ON
6,50 Fort York Blvd,Park,43.638762,-79.397067,Canoe Landing Park,M5V 3Z1,ON
7,500 Gerrard St.,Park,43.666048,-79.360941,Riverdale Park West,M5A 2H3,ON
8,255 Bremner Blvd.,Park,43.641745,-79.384279,Roundhouse Park,M5V 3M9,ON
9,875 Dufferin St,Park,43.656052,-79.431915,Dufferin Grove Park,M6H,ON
10,110 Chestnut Street,American Restaurant,43.654884,-79.385931,Hemispheres Restaurant & Bistro,M5G 1R3,ON
11,225 Frnt St W,Restaurant,43.644749,-79.385113,Azure Restaurant & Bar,M5V 2X3,ON
12,323 Spadina Ave.,Dim Sum Restaurant,43.654318,-79.398650,Rol San Restaurant 龍笙棧,M5T 2E9,ON
13,309 Spadina Ave.,Chinese Restaurant,43.653866,-79.398334,Swatow Restaurant 汕頭小食家,M5T 2E6,ON
14,266 Spadina Ave,Noodle House,43.652278,-79.398039,Goldstone Noodle Restaurant 金石,M5T 2E4,ON
15,301 Front St W,Wine Bar,43.642537,-79.387042,360 Restaurant,M5V 2T6,ON
16,287 King St. W,Indian Restaurant,43.646463,-79.389644,Aroma Fine Indian Restaurant,M5V 1J5,ON
17,353 Spadina Ave.,Chinese Restaurant,43.655337,-79.398897,New Sky Restaurant 小沙田食家,M5T 2G3,ON
18,195 Dundas St W,Chinese Restaurant,43.654925,-79.387089,Hong Shing Chinese Restaurant,M5G 1C7,ON
19,30 Mercer Street,Bar,43.645634,-79.391125,Victor Restaurant & Bar,M5V 1H3,ON
20,261 Spadina Avenue. Upper level,Chinese Restaurant,43.652488,-79.397501,Green Tea Restaurant Downtown,M5T 2E3,ON
21,35 Church St,American Restaurant,43.648824,-79.373702,The Hot House Restaurant & Bar,M5E 1T3,ON
22,37 King Street East,Restaurant,43.649298,-79.376431,Victoria's Restaurant,M5C 1E9,ON
23,100 Cumberland Street,Event Space,43.670342,-79.391041,Sassafraz | Cafe | Restaurant | Private Events,M5R 1A6,ON
24,405 Spadina Ave,Caribbean Restaurant,43.656794,-79.399251,Tasty's Caribbean Restaurant & Catering,M5T 2G6,ON
25,14 Queen St W,Restaurant,43.652614,-79.380231,Richtree Natural Market Restaurants,M5H 3X4,ON
26,1132 Dundas St. W,Diner,43.649435,-79.420390,The Lakeview Restaurant,M6J 1X2,ON
27,563 Bloor St West,Restaurant,43.665180,-79.410966,Insomnia Restaurant and Lounge,M5S 1Y6,ON
28,8 St Andrew St.,Korean Restaurant,43.654307,-79.399277,Ka Chi Korean Restaurant,M5T 1K6,ON
29,293 Palmerston Ave.,New American Restaurant,43.655765,-79.409929,Woodlot Restaurant & Bakery,M6J 2J3,ON
30,90 Bloor St.,Restaurant,43.670574,-79.384856,Matisse Restaurant And Bar,M4W 1A7,ON
31,389 Church St.,Breakfast Spot,43.661500,-79.379319,Studio Restaurant,M5B,ON
32,249 Victoria Street,Diner,43.655641,-79.379199,The Senator Restaurant,M5B 1T8,ON
33,2A Kensington Ave.,Breakfast Spot,43.652803,-79.399958,Kensington Cornerstone Restaurant,M5T 2J7,ON
34,145 Richmond Street West,Restaurant,43.650010,-79.385608,Tundra Restaurant,M5H 2L2,ON
35,338 Jarvis St.,Thai Restaurant,43.662770,-79.376894,Cottage Restaurant & Lounge,M4Y 2G6,ON
36,388 Spadina Ave,Asian Restaurant,43.655454,-79.399163,Stay Cafeteria 慢走,M5T 2G5,ON
37,974 College St,Mexican Restaurant,43.653419,-79.427678,Cafeteria,M6H 1A5,ON
38,131 Farnham Avenue,College Cafeteria,43.683003,-79.397815,De La Salle College Cafeteria,M4V 1H7,ON
39,51 Dockside Dr,Community College,43.644163,-79.366375,George Brown College St. James Campus,M5A 0B6,ON
40,30 Bond St.,Restaurant,43.653585,-79.378843,Marketeria,M5B 1W8,ON
41,350 Victoria St.,College Cafeteria,43.658585,-79.380622,The Hub,M5B 2K3,ON
42,2 Sussex Ave,Student Center,43.665556,-79.399298,Innis College,M5S 1J5,ON
43,435 Spadina Ave.,Chinese Restaurant,43.657399,-79.399649,One Hour,M5T 2T6,ON

In [48]:
# Generate map to visualize park neighbourhood including Restaurant and Cafeteria 
park_map = folium.Map(location=[latitude, longitude], zoom_start=14)

for lat, lng, name, categories, address in zip(park_neighbourhood_df['lat'], park_neighbourhood_df['lng'], 
                                           park_neighbourhood_df['name'], park_neighbourhood_df['categories'],\
                                               park_neighbourhood_df['address']):
    label = '{}, {}'.format(name, address)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='blue',
        fill_opacity=0.7,
        parse_html=False).add_to(park_map)  
    
park_map